### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by johnhof** [johnhof/proxy-express#2]
I think the best approach here would be to use supertest.

we should go about this 2 ways:
- `unit test script`\- call `proxy()`  in the test script, making sure all config values work/apply, by checking  `proxyObj.reqOpts` using the `pre` middleware hook
- `user test script` - run a server, call various proxies and make sure the response from the 3rd party API proxy matches the response from an isolated `request()` for the same endpoint directly to the 3rd party API

**Comment by johnhof** [comment]
@NickMele feedback on this test setup?

**Comment by NickMele** [comment]
Do we plan on having a set of API's that this will work for, or should it essentially work for any API endpoint?

I think the second case is a great test, but unless we know of every different API endpoint i don't think it will guarantee that every one will work properly.

**Comment by johnhof** [comment]
well its supposed to just take the request and straight proxy it to whatever server you specify, so it should work no matter what site youre working. Obviously some APIs will require request settings accross the board, which is what the configurations and `pre` request hook are for

**Comment by NickMele** [comment]
but thats what i mean, is it going to be worth writing tests for some API "X" and "Y" to make sure that they work correctly when we are not sure if our test will cover API "Z"

**Comment by johnhof** [comment]
yea I guess thats the debate. maybe only write those tests for any express-proxy pre defined configurations.

I meant to have those use-tests run as a smoke test in case our proxy isnt a 100% match. But that will come automatically if we implement a set of pre-supported API configurations

**Comment by NickMele** [comment]
Yeah we can do that. I think the first case is the most important though. If we can confirm that the developer can leverage the configurations to make essentially any API work.

**Comment by johnhof** [comment]
right right. I just dont think it would hurt to have a smoke test to make sure the product works end to end, in its actual environment (a live express server). Maybe just stand up a second server locally and forward to that server?

**Comment by NickMele** [comment]
Yeah i agree with that, just saying we shouldn't expect that to cover every API

**Comment by johnhof** [comment]
oh yea... absolutely not haha. thats way more work than necessary

**Comment by NickMele** [comment]
for case 1 we should also test to make sure that the actual request that goes out contains the values we are applying. not sure if that is what you meant.

**Comment by johnhof** [comment]
i was leaving that abstracted, but thats not a bad idea. I'm not 100% on how we would do that exactly. is there a node utility that lets us look at the wire?  I was just planning on something like: 

``` javascript
it('should set user agent', function (done) {
  var testUa = 'TEST';
  var middleware = proxy('someapi.com', {
    headers : {
      'User-Agent' :testUa
    }, 
    digest :
      pre : function (proxyObj, callback) {
         expect(proxyObj.reqOpts.headers['User-Agent']).to.equal(testUa)
         done();
      } 
  });

  middleware({}, {}, function () {});
});
```

**Comment by johnhof** [comment]
Though I suppose we could construct a fake req and res so proxy makes the request, then check the `proxyObj.reqOpts.result.response.request.headers` (thats a mouthful) in the `digest.post middleware.

that way we could see the request that was actually sent

**Comment by NickMele** [comment]
Yeah that is actually what i was thinking. just using the response object to check to make sure that we wanted to send was actually what got sent and used by the API

**Comment by johnhof** [comment]
implemented
