### ISSUE TITLE
Proxy Strips Form Data

### ISSUE THREAD

**Issue by stephenHartzell** [johnhof/proxy-express#24]
I am using proxy-express to proxy to a django backend. After quite a bit of debugging and testing with postman and looking at the logs, I discovered that proxy-express strips request form data. If I'm just missing something please let me know.

app.use(proxy(ADMIN_HOST+ '/admin', {
  prefix : '/admin',
  log: true,
  request : {
    headers : {
      'X-Forwarded-Host' : 'localhost:' + port,
    }
  }
}));

**Comment by afhammad** [comment]
@DuaneGarber why no love for the PUT method?
