### ISSUE TITLE
Upgrade Node to be 4.x

### ISSUE THREAD

**Issue by DuaneGarber** [johnhof/proxy-express#28]
Node 0.10 is EOLing: https://github.com/nodejs/LTS/issues/31

So I propose we do a major rev bump to 2.0

As a first pass I will just update the simple stuff and then we can start utilizing the ES 2015 changes more in depth on subsequent PRs. 

I picked 4.x over 5 just simply because its a LTS so its a better target for any module.

**Comment by johnhof** [comment]
yea, the gains from 4-5 arent that extreme that I feel like we need the latest version. LTS would be better
