### ISSUE TITLE
Expand options

### ISSUE THREAD

**Issue by johnhof** [johnhof/proxy-express#6]
the following config options should be supported

``` javascript
server.use(proxy(host, [bool to force https])); // DONE
```

``` javascript
server.use(proxy(host, String /*remove from path when actual request is made*/, Boolean /*to force https*/); // DONE
```

``` javascript
server.use(proxy(host, RegExp /*only proxy request urls that match regex*/, [bool to force https]));
```

``` javascript
server.use(proxy(host, {
  forceHttps : Boolean, // DONE
  prefix  : String, // remove from path when actual request is made // DONE
  match : RegExp // only proxy request urls that match regex
  headers : {} // headers to override client submitted  // DONE
  cookies :  {} // cookies to override client submitted
  passthrough : { // cases which ignore digest
    files : ['File Extension'],
    match : RegExp
  }
  digest : {
    pre : function (proxyObj, callback) {
      // res & res available through proxyObj
    },
    post : function (proxyObj, callback) {
      // res & res available through proxyObj
    }
  }
}));
```

**Comment by johnhof** [comment]
@NickMele I marked the config options that are already implemented. Is there anythign you would like to add or change? I want ti to be as clear as possible

**Comment by NickMele** [comment]
for `pre` and `post`, what else is available in `proxyObj`? If it is just `req` and `res`, do we need the object?

**Comment by johnhof** [comment]
I wanted to maintain the express callback form, but we need a way for the user to access the proxied request object, and the proxy result. I'm open to alternatives though

initial definition https://github.com/johnhof/express-proxy/blob/master/lib/proxy.js#L146
addition of proxy results https://github.com/johnhof/express-proxy/blob/master/lib/proxy.js#L184

**Comment by NickMele** [comment]
Oh i see, i thought based on the description that `proxyObj` contained `req` and `res` but it looks like it just contains `response` and `body`

**Comment by johnhof** [comment]
yea, sorry. I havent updated docs or anything yet

**Comment by johnhof** [comment]
implemented. see readme for end result
